### ISSUE TITLE
Doesn't work on shadow rocket (iphone)

### ISSUE THREAD

**Issue by dusty-cjh** [myelectronix/xtls-reality-docker#2]
I'm a expirenced backend programmer.

After scanning the QR code, there do have a `MyVLESS` config in shadowrocket server list.

But we I try to reach any website, the page just doesn't loaded.

test:
1. visit by HTTP, I can see the `400 cloudflare fake page`
2. monitor on specific port by tcpdump, there do have some traffic.

by the way, I have the port mapping like this way: 12443:443, 
it won't generally affect the result right?

here is my docker compose file:
```yaml
version: '3.8'
services:
  xtls-reality:
    image:  myelectronix/xtls-reality:latest
    environment:
      - SNI=external.hdcjh.xyz
      - SHORT_ID=32f89a0f
    container_name: xtls-reality
    restart: always
    ports:
      - "443:443"
    volumes:
      - xtls-reality-volume:/opt/xray/config

volumes:
  xtls-reality-volume:
    external: true
    name: xtls-reality-volume
```
